In [3]:
import numpy as np
from keras.models import Sequential, Model
from keras.layers import Dense
from keras.optimizers import Adam, SGD

In [24]:
# Define the XOR function
x_train=np.array([[0,0],[0,1],[1,0],[1,1]])
y_train = np.array([[0], [1], [1], [0]])

# Define the model
model=Sequential()
# add the first (hidden) layer
model.add(Dense(2,input_dim=2,activation='sigmoid'))
# add the second (output) layer
model.add(Dense(1,activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy',
               optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=10000, verbose=0)

# Evaluate the model
loss, accuracy = model.evaluate(x_train, y_train)
print(f'Loss: {loss}, Accuracy: {accuracy}')

# Predict
predictions = model.predict(x_train)
print('Predictions:')
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.5000 - loss: 0.3514
Loss: 0.3514099717140198, Accuracy: 0.5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
Predictions:
[[0.00492713]
 [0.49764493]
 [0.99227744]
 [0.50096524]]


We need at least two hidden units given the proof from the last sheet. The accuracy is quite low, however.

In [30]:
# Define the XOR function
x_train=np.array([[0,0],[0,1],[1,0],[1,1]])
y_train = np.array([[0], [1], [1], [0]])

# Define the model
model=Sequential()
# add the first (hidden) layer
model.add(Dense(2,input_dim=2,activation='sigmoid'))
# add the second (output) layer
model.add(Dense(1,activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy',
               optimizer=SGD(), metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=10000, verbose=0)

# Evaluate the model
loss, accuracy = model.evaluate(x_train, y_train)
print(f'Loss: {loss}, Accuracy: {accuracy}')

# Predict
predictions = model.predict(x_train)
print('Predictions:')
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.7500 - loss: 0.6621
Loss: 0.6620842814445496, Accuracy: 0.75
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
Predictions:
[[0.49148676]
 [0.43167147]
 [0.6067716 ]
 [0.4686741 ]]


Worse prediction using a SGD optimiser instead of ADAM and higher loss (but also higher accuracy?)

We try again using ADAM but with 4 hidden units/neurons/nodes instead of 2

In [4]:
# Define the XOR function
x_train=np.array([[0,0],[0,1],[1,0],[1,1]])
y_train = np.array([[0], [1], [1], [0]])

# Define the model
model=Sequential()
# add the first (hidden) layer
model.add(Dense(4,input_dim=2,activation='sigmoid',name='hidden_layer'))
# add the second (output) layer
model.add(Dense(1,activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy',
               optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=10000, verbose=0)

# Evaluate the model
loss, accuracy = model.evaluate(x_train, y_train)
print(f'Loss: {loss}, Accuracy: {accuracy}')

# Predict
predictions = model.predict(x_train)
print('Predictions:')
print(predictions)

# Create a new model that outputs the activations of the hidden layer
hidden_layer_model = Model(inputs=model.input, outputs=model.get_layer('hidden_layer').output)

# Get the activations of the hidden layer
hidden_layer_activations = hidden_layer_model.predict(x_train)
print('Hidden Layer Activations:')
print(hidden_layer_activations)

c:\Users\fayza\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 1.0000 - loss: 0.0309
Loss: 0.03085966408252716, Accuracy: 1.0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
Predictions:
[[0.00378153]
 [0.9700734 ]
 [0.9705625 ]
 [0.05765798]]


AttributeError: The layer sequential has never been called and thus has no defined input.

We have 100% accuracy with 4 hidden units, a very low loss and good predictions. 

the network parameters/model parameters are the weights and biases. We can view them with model.summary():

In [34]:
model.summary()

Model: "sequential_27"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_54 (Dense)                │ (None, 4)              │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_55 (Dense)                │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 53 (216.00 B)

 Trainable params: 17 (68.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 36 (148.00 B)

In [35]:
# View the network parameters
for layer in model.layers:
    weights, biases = layer.get_weights()
    print(f'Layer: {layer.name}')
    print(f'Weights:\n{weights}')
    print(f'Biases:\n{biases}')


Layer: dense_54
Weights:
[[ 7.7802315  4.834136   4.9611077 -6.1661067]
 [ 9.053175   2.5164917  2.6173427  5.9073358]]
Biases:
[-4.2679777 -5.9049335 -6.054908   4.178037 ]
Layer: dense_55
Weights:
[[ 7.368208 ]
 [-5.4062304]
 [-5.434144 ]
 [-5.115242 ]]
Biases:
[1.5228887]
